# -*- coding: utf-8 -*-
"""LoadData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WcnSMxPNKzu3iyd6d8APCfsnEKl1XkO8
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import os
import pickle

os.name

data_directory_path = "/content/drive/My Drive/Colab Notebooks/CS7IS2 - Artificial Intelligence/Data"
features_path = "/content/drive/My Drive/Colab Notebooks/CS7IS2 - Artificial Intelligence/features"
labels_path = "/content/drive/My Drive/Colab Notebooks/CS7IS2 - Artificial Intelligence/labels"

dataset = os.listdir(data_directory_path)
dataset

data = []
data_load = []
y = []
y_load = []

def load_data():
  ctr=0
  for file in dataset:
    file = data_directory_path + "/" + file
    data = np.load(file)
    # print (file + ":")
    # print (data.shape[0])
    # print (data)
    data = data.astype('float32') /255
    data = data[0:10000, :]
    # print (file + ":")
    # print (data.shape[0])
    # print (data)
    data_load.append(data)
    # print (data_load)
    y=[ctr for _ in range(10000)]
    ctr += 1
    y = np.array(y).astype('float32')
    y = y.reshape(y.shape[0], 1)
    y_load.append(y)
  # print (y_load)
  return data_load, y_load

features, labels = load_data()

# features[1][1]

labels[14][0]
# labels.shape

features = np.array(features).astype('float32')
features.shape

labels = np.array(labels).astype('float32')
labels.shape

features = features.reshape(features.shape[0]*features.shape[1], features.shape[2])
features.shape

labels=labels.reshape(labels.shape[0]*labels.shape[1],labels.shape[2])
labels.shape

file = open(features_path,"wb")
try:
  pickle.dump(features, file, protocol=4)
finally:
  file.close()

file2 = open(labels_path, "wb")
try:
  pickle.dump(labels, file2, protocol=4)
finally:
    file2.close()